
DROP TABLE IF EXISTS `master_device_history`;
CREATE TABLE `master_device_history` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `device_id` bigint(20) NOT NULL,
  `serial` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `imei` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `mac` varchar(30) COLLATE utf8_unicode_ci DEFAULT NULL,
  `product_name` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `fw` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `state` tinyint(4) DEFAULT '0',
  `area_id` int(5) DEFAULT NULL,
  `area_name` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `export_date` bigint(20) DEFAULT NULL,
  `delivery_date` bigint(20) DEFAULT NULL,
  `active_date` bigint(20) DEFAULT NULL,
  `expired_date` bigint(20) DEFAULT NULL,
  `guarantee_export_date` bigint(20) DEFAULT NULL,
  `guarantee_import_date` bigint(20) DEFAULT NULL,
  `recall_date` bigint(20) DEFAULT NULL,
  `export_code` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `customer_code` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pricing_code` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pricing_cycle` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pricing_begin_date` bigint(20) DEFAULT NULL,
  `pricing_end_date` bigint(20) DEFAULT NULL,
  `pricing_pause_date` bigint(20) DEFAULT NULL,
  `pricing_change_date` bigint(20) DEFAULT NULL,
  `subscription_status` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `origin_contract` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `origin_po` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `contract` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `po` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `origin_agency` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `agency` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `location_code` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `location_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `accounting_code` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `inventory_transfer_number` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `customer_type` tinyint(4) DEFAULT '1',
  `created_by` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `updated_by` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created` bigint(20) DEFAULT NULL,
  `updated` bigint(20) DEFAULT NULL,
  `active` tinyint(4) DEFAULT '1',
  `tenant_id` bigint(20) DEFAULT '0',
  `origin_contract_id` bigint(20) DEFAULT NULL,
  `contract_id` bigint(20) DEFAULT NULL,
  `project` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `project_id` bigint(20) DEFAULT NULL,
  `current_area_id` bigint(20) DEFAULT NULL,
  `current_area_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC;
